server.port=${PORT:8082}
spring.application.name=iron-ledger-backend

# --- Neon Cloud PostgreSQL Connection ---
spring.datasource.url=jdbc:postgresql://ep-fragrant-cell-aomcdmus.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Hibernate (JPA) Configuration ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# --- Resend Email API ---
resend.api.key=${RESEND_API_KEY}
app.frontend.url=${FRONTEND_URL:https://iron-ledger-nishant.vercel.app}